package com.maroontress.clione.macro;

import java.util.List;

import com.maroontress.clione.Token;

/**
    Thrown to indicate that an invalid preprocessing token is generated by
    the '##' operator.
*/
public final class InvalidPreprocessingTokenException
        extends MacroExpansionException {

    private static final long serialVersionUID = 1L;

    /**
        Creates a new instance.

        @param tokenString The string representation of the invalid token.
        @param expandingTokens The list of tokens that represents the macro
        expansion stack.
    */
    public InvalidPreprocessingTokenException(String tokenString,
            List<Token> expandingTokens) {
        super(newMessage(tokenString, expandingTokens.get(0)),
            expandingTokens);
    }

    private static String newMessage(String tokenString, Token causeToken) {
        return String.format("%s: error: pasting forms '%s', an invalid "
                + "preprocessing token",
            causeToken.getSpan().getStart(),
            tokenString);
    }
}
