package com.maroontress.clione;

import java.util.List;

/**
    Thrown to indicate that an invalid preprocessing token is generated by
    the '##' operator.
*/
public final class InvalidPreprocessingTokenException extends
        MacroExpansionException {

    private static final long serialVersionUID = 1L;

    /**
        Creates a new instance.

        @param message The detail message.
        @param expandingTokens The list of tokens that represents the macro
        expansion stack.
    */
    public InvalidPreprocessingTokenException(String message,
            List<Token> expandingTokens) {
        super(newMessage(message, expandingTokens.get(0)), expandingTokens);
    }

    private static String newMessage(String message, Token causeToken) {
        return String.format("%s: error: %s",
                causeToken.getSpan().getStart(),
                message);
    }
}
